In [1]:
import pandas as pd 
import numpy as np

In [6]:
url_desocupados="https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV"
url_ocupados= "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV"
url_ft="https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV"
url_cgsse=" https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV"

# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

In [8]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [10]:
df_cgsse[["PERIODO", "FEX_C18"]]

        PERIODO    FEX_C18
0      20250626  67.484133
1      20250626  67.484133
2      20250626  54.337978
3      20250626  54.337978
4      20250626  54.337978
...         ...        ...
67851  20250626  47.033269
67852  20250626  47.033269
67853  20250626  32.850300
67854  20250626  32.850300
67855  20250626  32.850300

[67856 rows x 2 columns]

In [20]:
PT= df_cgsse[["FEX_C18"]].sum()

In [21]:
df_ft[["FEX_C18"]].sum()

FEX_C18    4.065342e+07
dtype: float64

In [22]:
df_ocupados[["FEX_C18"]].sum()

FEX_C18    2.375295e+07
dtype: float64

In [23]:
PH = df_cgsse[df_cgsse['P3271']==1]['FEX_C18'].sum()
PM = df_cgsse[df_cgsse['P3271']==2]['FEX_C18'].sum()
print(f' Hombres : {PH}')
print(f' Mujeres:  {PM}')

 Hombres : 25304270.000003804
 Mujeres:  26740731.000005245

In [24]:
PH/PT*100

FEX_C18    48.619982
dtype: float64

In [26]:
PTQ = df_cgsse[df_cgsse['DPTO']==63]['FEX_C18'].sum()
PTQ

np.float64(603068.649439007)

In [27]:
PHQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==1)]['FEX_C18'].sum()
PMQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==2)]['FEX_C18'].sum()
print(f' Hombres del Quindio : {PHQ}')
print(f' Mujeres del Quindio:  {PMQ}')

 Hombres del Quindio : 297925.64044618
 Mujeres del Quindio:  305143.00899282703

In [31]:
PHQ/PTQ*100

np.float64(49.40161302089233)

In [32]:
PMQ/PTQ*100

np.float64(50.598386979107666)