In [2]:
import pandas as pd 
import numpy as np

In [3]:
url_desocupados="https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV"
url_ocupados= "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV"
url_ft="https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV"
url_cgsse=" https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV"

# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

In [4]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [5]:
df_cgsse[["PERIODO", "FEX_C18"]]

        PERIODO    FEX_C18
0      20250626  67.484133
1      20250626  67.484133
2      20250626  54.337978
3      20250626  54.337978
4      20250626  54.337978
...         ...        ...
67851  20250626  47.033269
67852  20250626  47.033269
67853  20250626  32.850300
67854  20250626  32.850300
67855  20250626  32.850300

[67856 rows x 2 columns]

In [6]:
PT= df_cgsse[["FEX_C18"]].sum()

In [7]:
PET=df_ft[["FEX_C18"]].sum()

In [8]:
df_ocupados[["FEX_C18"]].sum()

FEX_C18    2.375295e+07
dtype: float64

In [9]:
PH = df_cgsse[df_cgsse['P3271']==1]['FEX_C18'].sum()
PM = df_cgsse[df_cgsse['P3271']==2]['FEX_C18'].sum()
print(f' Hombres : {PH}')
print(f' Mujeres:  {PM}')

 Hombres : 25304270.000003804
 Mujeres:  26740731.000005245

In [10]:
PH/PT*100

FEX_C18    48.619982
dtype: float64

In [11]:
PTQ = df_cgsse[df_cgsse['DPTO']==63]['FEX_C18'].sum()
PTQ

np.float64(603068.649439007)

In [12]:
PHQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==1)]['FEX_C18'].sum()
PMQ = df_cgsse[(df_cgsse['DPTO']==63) & (df_cgsse['P3271']==2)]['FEX_C18'].sum()
print(f' Hombres del Quindio : {PHQ}')
print(f' Mujeres del Quindio:  {PMQ}')

 Hombres del Quindio : 297925.64044618
 Mujeres del Quindio:  305143.00899282703

In [13]:
PHQ/PTQ*100

np.float64(49.40161302089233)

In [14]:
PMQ/PTQ*100

np.float64(50.598386979107666)

In [15]:
# P6040 :  poblacion en edad de trabajar 
df_cgsse[df_cgsse['P6040']>=15]['FEX_C18'].sum()

np.float64(40653416.00000409)

In [16]:
# P6040 :  poblacion que no esta en edad a trabajar 
df_cgsse[df_cgsse['P6040']< 15]['FEX_C18'].sum()

np.float64(11391585.000004958)

In [17]:
#FT: Pertenece a la PEA: .sum()si: 1
PEA=df_ft[(df_ft['FT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Activa {PEA}')

Población Economicamente Activa 25974846.22356785

In [18]:
#FFT Pertenece a la PEI  si:1
PEI=df_ft[(df_ft['FFT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Inactiva {PEI}')

Población Economicamente Inactiva 14678569.776436238

In [19]:
#OCI : Ocupado ? 1:si
O=df_ocupados[(df_ocupados['OCI']==1)]['FEX_C18'].sum()
print(f'Población Ocupada {O}')




TO=O/PET*100
print(f' Tasa de ocupacion para Diciembre de 2024 {round(TO,1)}')

Población Ocupada 23752952.660255846
 Tasa de ocupacion para Diciembre de 2024 FEX_C18    58.4
dtype: float64

In [20]:
#OCI : Ocupado ? 1:si
D=df_desocupados[(df_desocupados['DSI']==1)]['FEX_C18'].sum()
print(f'Población No ocupada {D}')

TD=D/PEA*100
print(f' Tasa de desempleo para diciembre de 2024 : {round(TD,1)}')

Población No ocupada 2221893.563312005
 Tasa de desempleo para diciembre de 2024 : 8.6

In [21]:
df_desocupados = pd.merge(df_desocupados, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

df_ft = pd.merge(df_ft, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [22]:
# 1. Calcular cantidad de hombres desempleados en el quindío 
HDQ = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==63) & (df_desocupados['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Quindio: {HDQ}')

# 2. Calcular cantidad de hombres en la PEA del quindío
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el quindío: {PEAHQ}')

# 3. Calcular la tasa de desempleo en hombres del quindío
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del quindío: {TDHQ*100}%')

Hombres Desempleados en el Quindio: 17869.520960767004
Poblacion Economicamente Activa de hombres en el quindío: 174625.87195169798
Tasa de Desempleo en hombres del quindío: 10.233031773040919%

In [23]:
# 1. Calcular cantidad de MUJERES desempleadas en el quindío 
MDQ = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==63) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en el Quindio: {MDQ}')

# 2. Calcular cantidad de mujeres en la PEA del quindío
PEAMQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en el quindío: {PEAMQ}')

# 3. Calcular la tasa de desempleo en mujeres del quindío
TDMQ = MDQ/PEAMQ
print(f'Tasa de Desempleo en mujeres del quindío: {TDMQ*100}%')

Mujeres Desempleadas en el Quindio: 10618.534945967001
Poblacion Economicamente Activa de mujeres en el quindío: 116885.879263648
Tasa de Desempleo en mujeres del quindío: 9.084531863781265%

In [24]:
# TASA DE DESEMPLEO DE HOMBRES EN RISARALDA
HDR = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==66) & (df_desocupados['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Risaralda: {HDR}')


PEAHR = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el Risaralda: {PEAHR}')


TDHR = HDR/PEAHR
print(f'Tasa de Desempleo en hombres del Risaralda: {TDHR*100}%')




#TASA DE  DESEMPLEO EN MUEJERS EN RISARALDA
MDR = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==66) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en  Risaralda: {MDR}')

PEAR = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en  risaralda: {PEAR}')


TDMR = MDR/PEAR
print(f'Tasa de Desempleo en mujeres del quindío: {TDMR*100}%')

Hombres Desempleados en el Risaralda: 18000.60370715
Poblacion Economicamente Activa de hombres en el Risaralda: 296342.328368219
Tasa de Desempleo en hombres del Risaralda: 6.074260064793518%
Mujeres Desempleadas en  Risaralda: 21676.799766712
Poblacion Economicamente Activa de mujeres en  risaralda: 203157.903399127
Tasa de Desempleo en mujeres del quindío: 10.669926891362644%

In [25]:
#TASA DE DESEMPLEO EN HOMBRES  EN TOLIMA

HDT = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==73) & (df_desocupados['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Tolima: {HDT}')


PEAHT = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el tolima: {PEAHT}')


TDHT = HDT/PEAHT
print(f'Tasa de Desempleo en hombres del tolima: {TDHT*100}%')




#TASA DE DESEMPLEO EN MUJERES  EN TOLIMA

MDT = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==73) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en  tolima: {MDR}')

PEAT = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en  TOLIMA: {PEAR}')


TDMT = MDR/PEAR
print(f'Tasa de Desempleo en mujeres del tolima: {TDMR*100}%')

Hombres Desempleados en el Tolima: 28255.96613253
Poblacion Economicamente Activa de hombres en el tolima: 391325.28931057
Tasa de Desempleo en hombres del tolima: 7.220582697916321%
Mujeres Desempleadas en  tolima: 21676.799766712
Poblacion Economicamente Activa de mujeres en  TOLIMA: 203157.903399127
Tasa de Desempleo en mujeres del tolima: 10.669926891362644%

In [26]:
#TASA DE DESEMPLEO EN HOMBRES  EN CALDAS
HDC = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==17) & (df_desocupados['P3271']==1)]['FEX_C18'].sum()

PEAC = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==1) ]['FEX_C18'].sum()

TDHC = HDC/PEAC
print(f'Tasa de Desempleo en hombres del caldas: {TDHC*100}%')

#TASA DE DESEMPLEO EN MUJERES  EN CALDAS
MDC = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['DPTO']==17) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()

PEMC = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==2) ]['FEX_C18'].sum()

TDMC = MDC/PEMC
print(f'Tasa de Desempleo en mujeres del caldas: {TDMC*100}%')

Tasa de Desempleo en hombres del caldas: 5.5831831601957065%
Tasa de Desempleo en mujeres del caldas: 7.677961547053494%

In [27]:
# 3 PUNTO 






#Segmento de 18 a 24 años de edad

# 1. Calcular cantidad personas desempleadas entre los 18 - 24 
D1824 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=24) & (df_desocupados['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 18 - 24 años: {D1824}')

# 2. Calcular cantidad personas en la PEA entre los 18 - 24
PEA1824 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: {PEA1824}')

# 3. Calcular la tasa de desempleo en personas entre los 18 - 24 del quindío
TD1824 = D1824/PEA1824
print(f'Tasa de Desempleo en personas entre los 18 - 24 del quindío: {TD1824*100}%')


#Segmento de 24 a 30 años de edad

D2430 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=24) & (df_desocupados['P6040']<=30) & (df_desocupados['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 24 - 30 años: {D2430}')

PEA2430 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 24 - 30 años: {PEA2430  }')

TD2430 = D2430/PEA2430
print(f'Tasa de Desempleo en personas entre los 24 - 30 del quindío: {TD2430*100}%')


#Segmento de 30 a 40 años de edad

D3040 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=30) & (df_desocupados['P6040']<=40) & (df_desocupados['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 30 - 40 años: {D3040}')

PEA3040 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 30 - 40 años: {PEA3040  }')

TD3040 = D3040/PEA3040
print(f'Tasa de Desempleo en personas entre los 24 - 30 del quindío: {TD2430*100}%')


#segmento de 40 a 50 años de edad

D4050 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=40) & (df_desocupados['P6040']<=50) & (df_desocupados['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 40 - 50 años: {D4050}')

PEA4050 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 40 - 50 años: {PEA4050  }')

TD4050 = D4050/PEA4050
print(f'Tasa de Desempleo en personas entre los 40 - 50 del quindío: {TD4050*100}%')


#segmento de 60 en adelante

D60 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=60) & (df_desocupados['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío de 60 años en adelante: {D60}')

PEA60 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío de 60 años en adelante: {PEA60  }')

TD60 = D60/PEA60
print(f'Tasa de Desempleo en personas de 60 años en adelante del quindío: {TD60*100}%')

Personas Desempleadas en el quindío entre los 18 - 24 años: 3819.2724449800003
Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: 29912.663758397
Tasa de Desempleo en personas entre los 18 - 24 del quindío: 12.768078683423386%
Personas Desempleadas en el quindío entre los 24 - 30 años: 7008.068900358
Poblacion Economicamente Activa en el quindío entre los 24 - 30 años: 51117.425383347
Tasa de Desempleo en personas entre los 24 - 30 del quindío: 13.709745449427672%
Personas Desempleadas en el quindío entre los 30 - 40 años: 7015.512022579001

Poblacion Economicamente Activa en el quindío entre los 30 - 40 años: 72731.96687714598
Tasa de Desempleo en personas entre los 24 - 30 del quindío: 13.709745449427672%
Personas Desempleadas en el quindío entre los 40 - 50 años: 4416.562673204001
Poblacion Economicamente Activa en el quindío entre los 40 - 50 años: 70586.28939453498
Tasa de Desempleo en personas entre los 40 - 50 del quindío: 6.256969605695048%
Personas Desempleadas en el quindío de 60 años en adelante: 4297.130465619
Poblacion Economicamente Activa en el quindío de 60 años en adelante: 41690.707895215004
Tasa de Desempleo en personas de 60 años en adelante del quindío: 10.307165991086942%

In [28]:
#Segmento de 18 a 24 años de edad EN RISARALDA

D1824 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=24) & (df_desocupados['DPTO']==66)]['FEX_C18'].sum()


PEA1824 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==66)]['FEX_C18'].sum()


TD1824 = D1824/PEA1824
print(f'Tasa de Desempleo en personas entre los 18 - 24 del risaralda: {TD1824*100}%')

#Segmento de 24 a 30 años de edad EN RISARALDA
D2430 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=24) & (df_desocupados['P6040']<=30) & (df_desocupados['DPTO']==66)]['FEX_C18'].sum()


PEA2430 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==66)]['FEX_C18'].sum()


TD2430 = D2430/PEA2430
print(f'Tasa de Desempleo en personas entre los 24 - 30 del risaralda: {TD2430*100}%')

#Segmento de 30 a 40 años de edad EN RISARALDA
D3040 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=30) & (df_desocupados['P6040']<=40) & (df_desocupados['DPTO']==66)]['FEX_C18'].sum()

PEA3040 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD3040 = D3040/PEA3040
print(f'Tasa de Desempleo en personas entre los 30 - 40 del risaralda: {TD3040*100}%')

#segmento de 40 a 50 años de edad EN RISARALDA
D4050 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=40) & (df_desocupados['P6040']<=50) & (df_desocupados['DPTO']==66)]['FEX_C18'].sum()

PEA4050 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD4050 = D4050/PEA4050
print(f'Tasa de Desempleo en personas entre los 40 - 50 del risaralda: {TD4050*100}%')


#segmento de 60 en adelante EN RISARALDA
D60 = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=60) & (df_desocupados['DPTO']==66)]['FEX_C18'].sum()

PEA60 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

TD60 = D60/PEA60
print(f'Tasa de Desempleo en personas de 60 años en adelante del risaralda: {TD60*100}%')

Tasa de Desempleo en personas entre los 18 - 24 del risaralda: 14.79121665773423%
Tasa de Desempleo en personas entre los 24 - 30 del risaralda: 11.5837366742538%
Tasa de Desempleo en personas entre los 30 - 40 del risaralda: 6.447452329705859%
Tasa de Desempleo en personas entre los 40 - 50 del risaralda: 7.3356816001245955%
Tasa de Desempleo en personas de 60 años en adelante del risaralda: 3.6398607318240614%

In [29]:
#segmento de 18 a 24 años de edad EN TOLIMA
D1824T = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=24) & (df_desocupados['DPTO']==73) ]['FEX_C18'].sum()

PEA1824T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==73) ]['FEX_C18'].sum()

TD1824T = D1824T/PEA1824T
print(f'Tasa de Desempleo en mujeres entre los 18 - 24 del tolima: {TD1824T*100}%')

#segmento de 24 a 30 años de edad EN TOLIMA
D2430T = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=24) & (df_desocupados['P6040']<=30) & (df_desocupados['DPTO']==73)]['FEX_C18'].sum()

PEA2430T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

TD2430T = D2430T/PEA2430T
print(f'Tasa de Desempleo entre los 24 - 30 del tolima: {TD2430T*100}%')

#segmento de 30 a 40 años de edad EN TOLIMA
D3040T = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=30) & (df_desocupados['P6040']<=40) & (df_desocupados['DPTO']==73)]['FEX_C18'].sum()

PEA3040T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==73) ]['FEX_C18'].sum()

TD3040T = D3040T/PEA3040T
print(f'Tasa de Desempleoentre los 30 - 40 del tolima: {TD3040T*100}%')

#segmento de 40 a 50 años de edad EN TOLIMA
D4050T = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=40) & (df_desocupados['P6040']<=50) & (df_desocupados['DPTO']==73)]['FEX_C18'].sum()

PEA4050T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==73) ]['FEX_C18'].sum()

TD4050T = D4050T/PEA4050T
print(f'Tasa de Desempleo entre los 40 - 50 del tolima: {TD4050T*100}%')


#segmento de 60 en adelante EN TOLIMA
D60T = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=60) & (df_desocupados['DPTO']==73)]['FEX_C18'].sum()

PEA60T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==73) ]['FEX_C18'].sum()

TDMT = D60T/PEA60T
print(f'Tasa de Desempleo 60 años en adelante del tolima: {TDMT*100}%')

Tasa de Desempleo en mujeres entre los 18 - 24 del tolima: 19.817064699055017%
Tasa de Desempleo entre los 24 - 30 del tolima: 13.882960839796077%
Tasa de Desempleoentre los 30 - 40 del tolima: 12.247228061873246%
Tasa de Desempleo entre los 40 - 50 del tolima: 8.641041526465289%
Tasa de Desempleo 60 años en adelante del tolima: 9.458632182113549%

In [ ]:
#segmento de 18 a 24 años de edad EN CALDAS 

D1824C = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=24) & (df_desocupados['DPTO']==17)]['FEX_C18'].sum()

PEA1824C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD1824C = D1824C/PEA1824C
print(f'Tasa de Desempleo entre los 18 - 24 de caldas: {TD1824C*100}%')

#segmento de 24 a 30 años de edad EN CALDAS
D2430C = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=24) & (df_desocupados['P6040']<=30) & (df_desocupados['DPTO']==17)]['FEX_C18'].sum()

PEA2430C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD2430C = D2430C/PEA2430C  
print(f'Tasa de Desempleo entre los 24 - 30 de caldas: {TD2430C*100}%')

#segmento de 30 a 40 años de edad EN CALDAS
D3040C = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=30) & (df_desocupados['P6040']<=40) & (df_desocupados['DPTO']==17)]['FEX_C18'].sum()

PEA3040C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD3040C = D3040C/PEA3040C
print(f'Tasa de Desempleo entre los 30 - 40 de caldas: {TD3040C*100}%')


#segmento de 40 a 50 años de edad EN CALDAS
D4050C = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=40) & (df_desocupados['P6040']<=50) & (df_desocupados['DPTO']==17)]['FEX_C18'].sum()

PEA4050C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD4050C= D4050C/PEA4050C
print(f'Tasa de Desempleo entre los 40 - 50 de caldas: {TD4050C*100}%')

#segmento de 60 en adelante EN CALDAS
D60C = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=60) & (df_desocupados['DPTO']==17)]['FEX_C18'].sum()

PEA60C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

TD60C = D60C/PEA60C
print(f'Tasa de Desempleo 60 años en adelante del caldas: {TD60C*100}%')

Tasa de Desempleo entre los 18 - 24 de caldas: 9.344949005517167%
Tasa de Desempleo entre los 24 - 30 de caldas: 6.442118267858205%
Tasa de Desempleo entre los 30 - 40 de caldas: 5.719162060970324%
Tasa de Desempleo entre los 40 - 50 de caldas: 5.123140786732679%
Tasa de Desempleo 60 años en adelante del caldas: 4.060989381499756%

In [35]:
#4 PUNTO




#segmento entre los 18 y 25 años en mujeres en QUINDIO

D1825QM = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=25) & (df_desocupados['DPTO']==63) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()

PEA1825QM = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==63) & (df_ft['P3271']==2)]['FEX_C18'].sum()

TD1825QM = D1825QM/PEA1825QM
print(f'Tasa de Desempleo entre los 18 - 25 años en mujeres del quindío: {TD1825QM*100}%')


#segmento entre los 18 y 25 años en mujeres en RISARALDA

D1825RM = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=25) & (df_desocupados['DPTO']==66) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()

PEA1825RM = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==66) & (df_ft['P3271']==2)]['FEX_C18'].sum()

TD1825RM = D1825RM/PEA1825RM
print(f'Tasa de Desempleo entre los 18 - 25 años en mujeres del risaralda: {TD1825RM*100}%')


#segmento entre los 18 y 25 años en mujeres en TOLIMA

D1825TM = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=25) & (df_desocupados['DPTO']==73) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()

PEA1825TM = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==73) & (df_ft['P3271']==2)]['FEX_C18'].sum()

TD1825TM = D1825TM/PEA1825TM
print(f'Tasa de Desempleo entre los 18 - 25 años en mujeres del tolima: {TD1825TM*100}%')


#segmento entre los 18 y 25 años en mujeres en CALDAS

D1825CM = df_desocupados[(df_desocupados['DSI']==1) & (df_desocupados['P6040']>=18) & (df_desocupados['P6040']<=25) & (df_desocupados['DPTO']==17) & (df_desocupados['P3271']==2)]['FEX_C18'].sum()

PEA1825CM = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=25) & (df_ft['DPTO']==17) & (df_ft['P3271']==2)]['FEX_C18'].sum()

TD1825CM = D1825CM/PEA1825CM
print(f'Tasa de Desempleo entre los 18 - 25 años en mujeres del caldas: {TD1825CM*100}%')

Tasa de Desempleo entre los 18 - 25 años en mujeres del quindío: 7.468210722605588%
Tasa de Desempleo entre los 18 - 25 años en mujeres del risaralda: 22.992769133081296%
Tasa de Desempleo entre los 18 - 25 años en mujeres del tolima: 21.37807100891119%
Tasa de Desempleo entre los 18 - 25 años en mujeres del caldas: 14.50010240532998%